# Generated by Django 4.2.7 on 2023-11-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
