# Generated by Django 4.2.7 on 2023-11-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_market', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
