# Generated by Django 4.2.7 on 2023-12-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_market', '0005_remove_item_color_remove_vendor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='files/images'),
        ),
    ]
